name: Ivo Freriks
favicon: null
layout_spectrum: 0.301456541987136
typography_spectrum: 0.32524065487086773
title: 'Test '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-19315974-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b4e9b'
    - '#fefefe'
    - '#00a0e3'
    - '#7594c2'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
